version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: agomez95
      POSTGRES_PASSWORD: 150357
      POSTGRES_DB: warehouse
    networks:
      - backend
networks:
  backend:
